# 应用名称
spring:
  application:
    name: spring_data_jpa_demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stu_test?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: abc123

server:
  port: 8080


